### ISSUE TITLE
install

### ISSUE THREAD

**Issue by JABioinf** [GiuseppeTestaLab/SCanSNP#14]
Hi team from the Testa Lab, 
thank you for developing this tool. I wanted to deconvolute some samples and compare SCanSNP output with demuxlet, souporcell, etc.
I've run into an installation issue following the install through conda and pip3, as `pip3 install git/SCanSNP` outputed 
```
ERROR:` Invalid requirement: 'git/SCanSNP'
Hint: It looks like a path. File 'git/SCanSNP' does not exist."
```
Could you let me know if it requires additional steps on my side to install ?
I'll use the docker image meanwhile that seems to work.

**Comment by castaway1990** [comment]
Hey, sorry,  the documentation was bad, I've just updated it. You first need to clone and then specify the directory during the pip install, now following the documentation should work.

Thank you! 
Davide
